services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubiwhere
    ports:
      - "8000:8000"
    volumes:
      - .:/app

    depends_on:
      - db

  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_DB: traffic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
