# Generated by Django 5.2.6 on 2025-09-23 16:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoadSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "road",
                    django.contrib.gis.db.models.fields.LineStringField(
                        srid=4326, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrafficRecorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("avg_speed", models.FloatField()),
                (
                    "road_segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="traffic.roadsegment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
