# Generated by Django 5.2.6 on 2025-09-24 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0001_initial"),
        ("traffic", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trafficrecorder",
            options={"get_latest_by": "updated_at"},
        ),
        migrations.CreateModel(
            name="TrafficCarRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vehicles.car"
                    ),
                ),
                (
                    "road_segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="traffic.roadsegment",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sensors.sensor"
                    ),
                ),
            ],
        ),
    ]
