name: Backend CI/CD Pipeline

on:
  push:
    # branches: [ "main" ] 
  pull_request:
    # branches: [ "main" ] 

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:15-3.3
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgis://postgres:postgres@localhost:5432/test_db
      DJANGO_SETTINGS_MODULE: django_project.settings
      DB_HOST: postgres

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Create virtual environment
        run: uv venv .venv

      - name: Install dependencies with uv
        run: uv sync

      - name: Wait for PostGIS
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostGIS..."
            sleep 2
          done

      - name: Run migrations
        run: uv run python manage.py migrate

      - name: Run Django tests
        run: uv run python manage.py test

