name: Backend CI/CD Pipeline

on:
  push:
    # branches: [ "main" ] 
  pull_request:
    # branches: [ "main" ] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Create virtual environment
        run: uv venv .venv

      - name: Install dependencies with uv
        run: uv sync

      - name: Run Django tests
        run: uv run python manage.py test
